name: Deploy Raft-in-Motion

on:
  push:
    branches:
      - wings-in-motion

jobs:
  deploy:
    name: Deploy to EC2 via SSM
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send Deployment Command to EC2
        run: |
          aws ssm send-command \
            --region ${{ secrets.AWS_REGION }} \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying new version of Raft-in-Motion" \
            --parameters commands='
              docker stop raft-container || true &&
              docker rm raft-container || true &&
              docker pull ${{ secrets.DOCKER_USERNAME }}/raft-in-motion:latest &&
              docker run -d -p 8081:8081 --name raft-motion ${{ secrets.DOCKER_USERNAME }}/raft-in-motion:latest
          '
