name: Deploy Raft-in-Motion

on:
  push:
    branches:
      - wings-in-motion

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/raft-in-motion:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/raft-in-motion:latest

  deploy:
    name: Deploy to EC2 via SSM
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Send Deployment Command to EC2
        run: |
          aws ssm send-command \
            --region ${{ secrets.AWS_REGION }} \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying new version of Raft-in-Motion" \
            --parameters commands='
              docker stop raft-container || true &&
              docker rm raft-container || true &&
              docker pull ${{ secrets.DOCKER_USERNAME }}/raft-in-motion:latest &&
              docker run -d -p 8081:8081 --name raft-container ${{ secrets.DOCKER_USERNAME }}/raft-in-motion:latest
            '
